# Generated by Django 2.2.3 on 2019-07-15 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_doctor_token_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='ndays',
            field=models.IntegerField(blank=True, null=True, verbose_name='number of days'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Age',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='report',
            name='Hemoglobin',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)], verbose_name='Hemoglobin(0-60)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='Neutrophils',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(80), django.core.validators.MinValueValidator(0)], verbose_name='Neutrophil(0-80)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='basophils',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(1), django.core.validators.MinValueValidator(0)], verbose_name='basophils(0-1)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='eosinophils',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='eosinophils(0-10)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lymphocytes',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(0)], verbose_name='lymphocytes(0-60)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='monocytes',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='monocytes(0-10)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='platelets',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(400000), django.core.validators.MinValueValidator(0)], verbose_name='platelets(0-400000)'),
        ),
        migrations.AlterField(
            model_name='report',
            name='rbc',
            field=models.FloatField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(0)], verbose_name='rbc(0-7)'),
        ),
    ]
